CREATE TABLE COMPETICION(IDCOMPETICION INT,NOMBRE nvarchar(100),IDPAIS int,TYPE nvarchar(50),LOGO nvarchar(300),PRIMARY KEY(IDCOMPETICION),FOREIGN KEY (IDPAIS) REFERENCES PAIS(IDPAIS))
CREATE TABLE TEMPORADA(IDTEMPORADA INT,STARTDATE DATETIME,ENDDATE DATETIME,PRIMARY KEY (IDTEMPORADA))
CREATE TABLE VENUE(IDVENUE INT,NOMBRE nvarchar(100),CIUDAD nvarchar(100),IDPAIS INT,CAPACIDAD INT,PRIMARY KEY(IDVENUE),FOREIGN KEY (IDPAIS) REFERENCES PAIS(IDPAIS))
CREATE TABLE EQUIPO(IDEQUIPO int, NOMBRE nvarchar(100),ABREVIATURA nvarchar(5),IDPAIS int,LOGO nvarchar(300),IDVENUE INT, PRIMARY KEY(IDEQUIPO),FOREIGN KEY (IDPAIS) REFERENCES PAIS(IDPAIS),FOREIGN KEY(IDVENUE) REFERENCES VENUE(IDVENUE))

ALTER TABLE COMPETICION ADD PAIS NVARCHAR(70)
ALTER TABLE VENUE ADD PAIS NVARCHAR(70)
ALTER TABLE EQUIPO ADD PAIS NVARCHAR(70)
ALTER TABLE EQUIPO_PARTICIPA_COMPETICION ADD PUNTOS INT


CREATE TABLE COMPETICION_DURANTE_TEMPORADA(IDCOMPETICION INT,IDTEMPORADA INT,STARTDATE DATETIME,ENDDATE DATETIME
,PRIMARY KEY(IDCOMPETICION,IDTEMPORADA),FOREIGN KEY(IDCOMPETICION) REFERENCES COMPETICION(IDCOMPETICION),FOREIGN KEY (IDTEMPORADA) REFERENCES TEMPORADA(IDTEMPORADA))

CREATE TABLE EQUIPO_PARTICIPA_COMPETICION(IDCOMPETICION INT,IDTEMPORADA INT,IDEQUIPO INT
,PARTIDOSJUGADOS INT,PARTIDOSJUGADOSLOCAL INT,PARTIDOSJUGADOSVISITANTE INT,VICTORIAS INT,VICTORIASLOCAL INT,VICTORIASVISITANTE INT, EMPATES INT,EMPATESLOCAL INT ,EMPATESVISITANTE INT,DERROTAS INT,DERROTASLOCAL INT,DERROTASVISITANTE INT,GOLESMARCADOS INT,GOLESMARCADOSLOCAL INT,GOLESMARCADOSVISITANTE INT,GOLESENCAJADOS INT,GOLESENCAJADOSLOCAL INT,GOLESENCAJADOSVISITANTE INT,TARJETASAMARILLAS INT,TARJETASAMARILLASLOCAL INT,TARJETASAMARILLASVISITANTE INT,TARJETASROJAS INT,TARJETASROJASLOCAL INT,TARJETASROJASVISITANTE INT
,PRIMARY KEY(IDCOMPETICION,IDTEMPORADA,IDEQUIPO), FOREIGN KEY (IDCOMPETICION) REFERENCES COMPETICION(IDCOMPETICION),FOREIGN KEY (IDTEMPORADA) REFERENCES TEMPORADA(IDTEMPORADA),FOREIGN KEY (IDEQUIPO) REFERENCES EQUIPO(IDEQUIPO))


CREATE TABLE PARTIDO(IDPARTIDO INT,IDCOMPETICION INT,IDTEMPORADA INT,ARBITRO nvarchar(70),TIMEZONO nvarchar(20),STARTDATE DATETIME,IDVENUE INT,IDLOCAL INT,IDVISITANTE INT,
GOLESLOCALHF INT,GOLESVISITANTEHF INT,GOLESLOCALFT INT,GOLESVISITANTE INT,GOLESLOCALET INT,GOLESVISITANTEET INT,GOLESLOCALPENALTY INT,GOLESVISITANTEPENALTY INT,
PRIMARY KEY(IDPARTIDO),FOREIGN KEY (IDCOMPETICION) REFERENCES COMPETICION(IDCOMPETICION),FOREIGN KEY (IDTEMPORADA) REFERENCES TEMPORADA(IDTEMPORADA),FOREIGN KEY (IDVENUE) REFERENCES VENUE(IDVENUE),FOREIGN KEY(IDLOCAL)REFERENCES EQUIPO(IDEQUIPO),FOREIGN KEY(IDVISITANTE)REFERENCES EQUIPO(IDEQUIPO))