    ALTER PROCEDURE SP_PROCEDURE_PARTIDOS_COMP(@IDCOMPETICION INT, @TEMPORADA INT, @POSICION INT, @CANTIDAD INT, @NUMREGISTROS INT OUT)
AS
SELECT @NUMREGISTROS = COUNT(IDPARTIDO) FROM PARTIDO WHERE IDCOMPETICION = @IDCOMPETICION AND IDTEMPORADA = @TEMPORADA
SELECT IDPARTIDO, IDCOMPETICION, IDTEMPORADA, ARBITRO, TIMEZONE, STARTDATE, IDVENUE, IDLOCAL, IDVISITANTE, GOLESLOCALHF, GOLESVISITANTEHF, GOLESLOCALFT, GOLESVISITANTEFT, GOLESLOCALET, GOLESVISITANTEET, GOLESLOCALPENALTY, GOLESVISITANTEPENALTY, RONDA, ESTADO, ESTADOFINAL, ELAPSED, NOMBRELOCAL, NOMBREVISITANTE, LOGOLOCAL, LOGOVISITANTE, PAIS, PAISIMAGEN, NOMBRECOMPETICION,NOMBREVENUE FROM(
SELECT CAST(ROW_NUMBER() OVER(ORDER BY IDPARTIDO)AS INT) AS POSICION,
IDPARTIDO, IDCOMPETICION, IDTEMPORADA, ARBITRO, TIMEZONE, STARTDATE, IDVENUE, IDLOCAL, IDVISITANTE, GOLESLOCALHF, GOLESVISITANTEHF, GOLESLOCALFT, GOLESVISITANTEFT, GOLESLOCALET, GOLESVISITANTEET, GOLESLOCALPENALTY, GOLESVISITANTEPENALTY, RONDA, ESTADO, ESTADOFINAL, ELAPSED, NOMBRELOCAL, NOMBREVISITANTE, LOGOLOCAL, LOGOVISITANTE, PAIS, PAISIMAGEN, NOMBRECOMPETICION,NOMBREVENUE
FROM PARTIDO WHERE IDCOMPETICION = @IDCOMPETICION AND IDTEMPORADA = @TEMPORADA ) AS QUERY
WHERE QUERY.POSICION >=@POSICION AND QUERY.POSICION<(@POSICION+@CANTIDAD) ORDER BY  QUERY.STARTDATE DESC
GO

ALTER TABLE PARTIDO ADD NOMBREVENUE nvarchar(70) DEFAULT ''
UPDATE PARTIDO SET NOMBREVENUE =''  WHERE NOMBREVENUE IS NULL
ALTER TABLE PARTIDO ALTER COLUMN NOMBREVENUE nvarchar(70)  NOT NULL

ALTER TABLE COMPETICION ADD BANDERAPAIS nvarchar(100)
UPDATE COMPETICION SET BANDERAPAIS =''  WHERE BANDERAPAIS IS NULL
ALTER TABLE COMPETICION ALTER COLUMN BANDERAPAIS nvarchar(100)  NOT NULL

CREATE PROCEDURE SP_COMPETICIONES
AS
SELECT * FROM COMPETICION WHERE IDCOMPETICION=135 OR IDCOMPETICION=140 OR IDCOMPETICION=39 OR IDCOMPETICION=61 OR IDCOMPETICION=78  
GO

UPDATE COMPETICION SET BANDERAPAIS='https://media-2.api-sports.io/flags/it.svg' WHERE IDCOMPETICION=135
UPDATE COMPETICION SET BANDERAPAIS='https://media-1.api-sports.io/flags/fr.svg' WHERE IDCOMPETICION=61
UPDATE COMPETICION SET BANDERAPAIS='https://media-1.api-sports.io/flags/es.svg' WHERE IDCOMPETICION=140
UPDATE COMPETICION SET BANDERAPAIS='https://media-2.api-sports.io/flags/gb.svg' WHERE IDCOMPETICION=39
UPDATE COMPETICION SET BANDERAPAIS='https://media-2.api-sports.io/flags/de.svg' WHERE IDCOMPETICION=78

UPDATE LINEUPPLAYER SET POSICION='' WHERE POSICION IS NULL
ALTER TABLE LINEUPPLAYER ALTER COLUMN POSICION nvarchar(5) NOT NULL
